In [1]:
import numpy as np
import pandas as pd

## Missing Value 

In [2]:
data = pd.read_csv('E:\kuliah\data mining statistika\Tugas 3\BlackFriday_data.csv',sep=';')
data.describe()

User_ID   Occupation  Marital_Status  Product_Category_1  \
count  1.000000e+03  1000.000000     1000.000000         1000.000000   
mean   1.000091e+06     8.366000        0.509000            4.896000   
std    5.203707e+01     6.594659        0.500169            3.563409   
min    1.000001e+06     0.000000        0.000000            1.000000   
25%    1.000045e+06     3.000000        0.000000            1.000000   
50%    1.000092e+06     7.000000        1.000000            5.000000   
75%    1.000142e+06    15.000000        1.000000            8.000000   
max    1.000173e+06    20.000000        1.000000           18.000000   

       Product_Category_2  Product_Category_3      Purchase  
count          704.000000          324.000000   1000.000000  
mean             9.627841           12.750000   9582.467000  
std              5.033104            4.037268   5120.496575  
min              2.000000            3.000000    584.000000  
25%              5.000000            9.000000   5909.000000  
50%              8.000000           14.000000   8125.000000  
75%             14.000000           16.000000  13552.500000  
max             17.000000           18.000000  23792.000000

In [3]:
np.sum(data.isnull())

User_ID                         0
Product_ID                      0
Gender                          0
Age                             0
Occupation                      0
City_Category                   0
Stay_In_Current_City_Years      0
Marital_Status                  0
Product_Category_1              0
Product_Category_2            296
Product_Category_3            676
Purchase                        0
dtype: int64

In [4]:
data['Product_Category_2']=data['Product_Category_2'].fillna((data['Product_Category_2'].mean()))
data=data.drop('Product_Category_3',1)

In [5]:
np.sum(data.isnull())

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Purchase                      0
dtype: int64

In [17]:
data.to_csv('E:\kuliah\data mining statistika\Tugas 3\BlackFriday_1.csv')

In [26]:
data1=data
data1.head()
print(data1.shape)

(1000, 11)


## Missing Value, Outlier 

In [32]:
from scipy.stats import stats
z = np.abs(stats.zscore(data._get_numeric_data()))
print(z)
data2 = data[(z<3).all(axis=1)]
print(data2.shape)

[[1.73134386 0.24790023 1.01816496 0.53234104 0.         0.23690548]
 [1.73134386 0.24790023 1.01816496 1.09388222 0.85967566 1.09761696]
 [1.73134386 0.24790023 1.01816496 1.99459427 0.         1.59448409]
 ...
 [1.53719278 1.30989633 0.98215912 0.81311163 1.33360806 1.25744702]
 [1.55641947 0.81409587 1.01816496 1.43305309 0.79908772 0.87682481]
 [1.57564616 1.26923705 0.98215912 2.27536486 1.50998631 1.7240285 ]]
(985, 11)


In [33]:
data2.to_csv('E:\kuliah\data mining statistika\Tugas 3\BlackFriday_2.csv')

## Missing Value, Transformasi 

In [36]:
x = data.iloc[0:1000,8:11] 
x.tail()

Product_Category_1  Product_Category_2  Purchase
995                   1                15.0     19696
996                   1                 8.0     15745
997                   2                 4.0     16018
998                  10                13.0     14070
999                  13                16.0       759

In [37]:
from sklearn.preprocessing import normalize
xnorm=normalize(x,norm='l2') 
xnorm=pd.DataFrame(xnorm) 
xnorm.tail()

0         1         2
995  0.000051  0.000762  1.000000
996  0.000064  0.000508  1.000000
997  0.000125  0.000250  1.000000
998  0.000711  0.000924  0.999999
999  0.017121  0.021073  0.999631

In [38]:
xnorm.to_csv('E:\kuliah\data mining statistika\Tugas 3\BlackFriday_3.csv')

In [53]:
print(xnorm.shape)

(1000, 3)


## Missing Value, Outlier, Transformasi

In [41]:
print(data2.shape)

(985, 11)


In [47]:
y=data2.iloc[0:986,8:11]
y.tail()

Product_Category_1  Product_Category_2  Purchase
995                   1                15.0     19696
996                   1                 8.0     15745
997                   2                 4.0     16018
998                  10                13.0     14070
999                  13                16.0       759

In [48]:
from sklearn.preprocessing import normalize
ynorm=normalize(y,norm='l2') 
ynorm=pd.DataFrame(ynorm) 
ynorm.tail()

0         1         2
980  0.000051  0.000762  1.000000
981  0.000064  0.000508  1.000000
982  0.000125  0.000250  1.000000
983  0.000711  0.000924  0.999999
984  0.017121  0.021073  0.999631

In [52]:
ynorm.to_csv('E:\kuliah\data mining statistika\Tugas 3\BlackFriday_4.csv')

In [54]:
print(ynorm.shape)

(985, 3)
